# Generated by Django 4.0 on 2022-06-02 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='is_valid',
        ),
    ]
