# Generated by Django 4.0 on 2022-06-03 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swap', '0003_user_prifile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='prifile_pic',
            new_name='profile_pic',
        ),
    ]
