# Generated by Django 4.0 on 2022-06-22 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swap', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('info', models.TextField(blank=True, max_length=256, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chatroom.message')),
                ('online', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='online', to='swap.user')),
            ],
        ),
    ]
