# Generated by Django 4.0 on 2022-06-22 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_alter_room_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chatroom.message'),
        ),
    ]
