# Generated by Django 4.0 on 2022-06-22 07:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatroom', '0003_alter_room_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='online',
        ),
        migrations.AddField(
            model_name='room',
            name='online',
            field=models.ManyToManyField(null=True, related_name='online', to=settings.AUTH_USER_MODEL),
        ),
    ]
