# Generated by Django 4.0 on 2022-06-22 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatroom', '0004_remove_room_online_room_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='message',
        ),
        migrations.AddField(
            model_name='room',
            name='message',
            field=models.ManyToManyField(to='chatroom.Message'),
        ),
        migrations.AlterField(
            model_name='room',
            name='online',
            field=models.ManyToManyField(related_name='online', to=settings.AUTH_USER_MODEL),
        ),
    ]
