# Generated by Django 4.0 on 2022-06-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0007_message_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
