# Generated by Django 4.0.6 on 2022-07-23 04:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatroom', '0008_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='message',
            field=models.ManyToManyField(related_name='messages', to='chatroom.message'),
        ),
        migrations.AlterField(
            model_name='room',
            name='online',
            field=models.ManyToManyField(related_name='onlines', to=settings.AUTH_USER_MODEL),
        ),
    ]
