# Generated by Django 4.0.6 on 2022-07-23 08:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0009_alter_message_time_alter_room_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 23, 8, 56, 10, 975962, tzinfo=utc), null=True),
        ),
    ]
