# Generated by Django 4.0.6 on 2022-08-12 01:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0010_alter_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 8, 12, 1, 3, 8, 82540, tzinfo=utc), null=True),
        ),
    ]
