/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/MZYVtNmyNgx
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export function Aviato() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32 bg-gradient-to-r from-blue-500 to-green-400">
      <nav className="container flex justify-between items-center mb-8 text-lg font-medium text-white">
        <div className="flex justify-around items-center space-x-4 border-b-2 border-white pb-2">
          <Link className="hover:text-yellow-300" href="#">
            Swap
          </Link>
          <Link className="hover:text-yellow-300" href="#">
            Liquidity Pool
          </Link>
          <Link className="hover:text-yellow-300" href="#">
            History
          </Link>
        </div>
        <Button
          className="inline-flex items-center space-x-2 border-white border-2 text-white hover:bg-white hover:text-black"
          variant="outline"
        >
          <svg
            className=" h-5 w-5 text-yellow-500"
            fill="none"
            height="24"
            stroke="currentColor"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2"
            viewBox="0 0 24 24"
            width="24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path d="M21 12V7H5a2 2 0 0 1 0-4h14v4" />
            <path d="M3 5v14a2 2 0 0 0 2 2h16v-5" />
            <path d="M18 12a2 2 0 0 0 0 4h4v-4Z" />
          </svg>
          <span>Connect Wallet</span>
        </Button>
      </nav>
      <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10">
        <div className="space-y-3">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl text-white">AviatoSwap</h2>
          <p className="mx-auto max-w-[700px] text-white md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            Swap your tokens in a decentralized and secure way.
          </p>
        </div>
        <form className="flex flex-col space-y-4 md:space-y-6">
          <Input className="max-w-lg flex-1" placeholder="Enter token to swap from" type="text" />
          <Input className="max-w-lg flex-1" placeholder="Enter token to swap to" type="text" />
          <Button type="submit">Swap</Button>
        </form>
        <div className="flex flex-col gap-2 min-[400px]:flex-row justify-center">
          <Link
            className="inline-flex h-10 items-center justify-center rounded-md bg-zinc-900 px-8 text-sm font-medium text-zinc-50 shadow transition-colors hover:bg-zinc-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-zinc-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-zinc-50 dark:text-zinc-900 dark:hover:bg-zinc-50/90 dark:focus-visible:ring-zinc-300"
            href="#"
          >
            Learn more
          </Link>
          <Link
            className="inline-flex h-10 items-center justify-center rounded-md border border-zinc-200 border-zinc-200 bg-white px-8 text-sm font-medium shadow-sm transition-colors hover:bg-zinc-100 hover:text-zinc-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-zinc-950 disabled:pointer-events-none disabled:opacity-50 dark:border-zinc-800 dark:border-zinc-800 dark:bg-zinc-950 dark:hover:bg-zinc-800 dark:hover:text-zinc-50 dark:focus-visible:ring-zinc-300"
            href="#"
          >
            Contact Support
          </Link>
        </div>
      </div>
    </section>
  )
}
